#!/usr/bin/env bash

# We want this entire script to exit if any single line fails.
# So we set the `-e` flag.
set -e

# If our deploy fails partway through we want to clean up after ourselves.
function cleanup_at_exit {
  # return to your master branch
  git checkout master
  
  # remove the deploy branch
  git branch -D deploy
}
trap cleanup_at_exit EXIT

# checks out a new branch called "deploy". 
git checkout -b deploy

# run build
npm run build

# "force" add the otherwise gitignored build files
git add -f build

# create a commit, even if nothing changed
git commit --allow-empty -m 'Deploying'

# push your local "deploy" branch to the "master" branch on heroku
git push --force heroku deploy:master